- name: Create directory
  ansible.builtin.file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    mode: '0755'

- name: Create a file
  ansible.builtin.template:
    src: my.cnf
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0600'
  no_log: true
  notify: restart mysql

- name: MySQL user backup
  community.mysql.mysql_user:
    name: backup
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"

- name: Create a file
  ansible.builtin.template:
    src: mysql-backup
    dest: /etc/cron.d/mysql-backup
    