- name: Install nginx
  apt: 
    name: nginx

- name: Copy file 
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    