- name: Install nginx
  apt: 
    name: nginx
    update_cache: yes

- name: Copy file 
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
    