- name: Reconfigure rsyslog
  ansible.builtin.template:
    src: 10-telegraf.conf.j2
    dest: /etc/rsyslog.d/10-telegraf.conf
  notify: Restart rsyslog


- name: Enable rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes