- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
  notify: Update apt packages

- name: Install grafana
  apt: 
    pkg:
      - grafana
  notify: Reset password

- name: Reconfigure Grafana
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Datasource Grafana
  ansible.builtin.template:
    src: sample.yaml
    dest: /etc/grafana/provisioning/datasources/sample.yaml

- name: Dashboard Grafana
  ansible.builtin.template:
    src: main.yaml
    dest: /etc/grafana/provisioning/dashboards/main.yaml

- name: Main settings json
  ansible.builtin.template:
    src: main.yaml
    dest: /var/lib/grafana/main.json
  notify: Restart grafana

- name: Enable grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes