- name: Install uwsgi
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3

- name: copy the uwsgi config file
  ansible.builtin.copy:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: restart uwsgi


- name: start uwsgi
  ansible.builtin.service:
    name: uwsgi
    state: started
    enabled: yes
