- name: Fix ssl bug for docker
  ansible.builtin.copy:
    src: iptables.mangle
    dest: /var/local/iptables.mangle
  #notify: Restore iptables

- name: Restore iptables
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle

- name: Install iptables-persistent
  apt: 
    name: iptables-persistent
    #/etc/iptables/rules.v4

- name: Saving iptables rules over reboot
  ansible.builtin.copy:
    src: iptables.mangle
    dest: /etc/iptables/rules.v4