- name: Add the user agama
  ansible.builtin.user:
    name: agama
    uid: 1045
    group: admin

- name: Create a directory 
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    mode: '0755'

- name: Install dependencies
  apt: 
    name: python3-flask-sqlalchemy
    name: python3-pymysql

- name: Download agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    mode: '0755'