---
- name: Stop Ubuntu systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped

- name: Change DNS configuration file
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf