- name: Create user backup 
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    


- name: Create  SSH key for user backup 
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Create directory
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0700'

- name: Install duplicity
  apt: 
    pkg:
      - duplicity

- name: Create a file
  ansible.builtin.template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    mode: '0600'

