- name: Create user backup 
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash
    


- name: Create  SSH key for user backup 
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa