# # config file version
apiVersion: 1

datasources:
#   # <string, required> name of the datasource. Required
 - name: InfluxDB
#   # <string, required> datasource type. Required
   type: influxdb
#   # <string, required> access mode. direct or proxy. Required
   access: proxy

#   # <string> url
   url: http://Yanny358-1:8086
   database: latency
   isDefault: false
#   # <bool> allow users to edit datasources from the UI.
   editable: true