# # config file version
apiVersion: 1

datasources:

 - name: Prometheus
#   # <string, required> datasource type. Required
   type: prometheus
#   # <string, required> access mode. direct or proxy. Required
   access: proxy
#   # <int> org id. will default to orgId 1 if not specified
   orgId: 1
#   # <string> url
   url: http://prometheus:9090/prometheus/
   isDefault: true
#   # <bool> allow users to edit datasources from the UI.
   editable: false



 - name: InfluxDB-latency
#   # <string, required> datasource type. Required
   type: influxdb
#   # <string, required> access mode. direct or proxy. Required
   access: proxy

#   # <string> url
   url: http://influxdb:8086
   database: latency
   isDefault: false
#   # <bool> allow users to edit datasources from the UI.
   editable: true
   


 - name: InfluxDB-telegraf
#   # <string, required> datasource type. Required
   type: influxdb
#   # <string, required> access mode. direct or proxy. Required
   access: proxy

#   # <string> url
   url: http://influxdb:8086
   database: telegraf
   isDefault: false
#   # <bool> allow users to edit datasources from the UI.
   editable: true