- name: Install keepalived
  apt: 
    name: keepalived

- name: Create user keepalived_script 
  ansible.builtin.user:
    name: keepalived_script
    home: /home/keepalived_script
    shell: /bin/bash



- name: Copy file ha88.j2
  ansible.builtin.template:
    src: ha88.j2
    dest: /home/keepalived_script/vrrp_script
    owner: keepalived_script
    mode: '0755'
    

- name: Copy file keepalived.conf.j2
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived, haproxy
  

- name: start keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes