- name: Download and unarchive keepalived exporter
  ansible.builtin.unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create keepalived-exporter service
  ansible.builtin.template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
  notify: 
    - reload systemd
    - restart keepalived-exporter


- name: Start service keepalived-exporter, if not started
  service:
    name: keepalived-exporter
    state: started
    enabled: yes
