- name: Install haproxy exporter
  apt: 
    pkg:
      - prometheus-haproxy-exporter

- name: Copy file 
  ansible.builtin.template:
    src: exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: restart haproxy exporter

- name: Enable haproxy_exporter
  ansible.builtin.service:
    name: prometheus-haproxy-exporter
    state: started
    enabled: yes