- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Reset password
  shell: |
    sleep 30
    grafana-cli admin reset-admin-password {{grafana_pass}}

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
    
  