- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: Restart password
  ansible.builtin.command: grafana-cli admin reset-admin-password "{{ grafana_pass }}"

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
    
  