- name: Docker package
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker

- name: Log in to DockerHub
  community.docker.docker_login:
    username: yannybrown
    password: "{{ docker_password }}"
  no_log: true

- name: Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes