- name: Install bind9
  apt:
    pkg:
    - bind9

- name: Copy file options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Copy file db
  ansible.builtin.template:
    src: db.iptv.j2
    dest: /var/cache/bind/db.iptv
  notify: rndc reload

- name: Copy file local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9


- name: start bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes