- name: Install package "bind9"
  apt:
    name: 
      - bind9
      - python3-dnspython

- name: Copy new named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: true
  notify: restart bind9

- name: Copy db.iptv.cs
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.iptv.cs.j2
    dest: /var/cache/bind/db.{{ domain }}
    force: no
  notify: rndc reload

- name: Copy db.iptv_slave.cs
  when: inventory_hostname in groups['dns_slave']
  ansible.builtin.template:
    src: db.iptv_slave.cs.j2
    dest: /var/cache/bind/db.{{ domain }}
    force: no
    

- name: Copy db.reverse
  when: inventory_hostname in groups['dns_master']
  ansible.builtin.template:
    src: db.reverse.j2
    dest: /var/cache/bind/db.reverse
    force: no
  notify: rndc reload


- name: Copy new named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9

- name: Force all notified handlers to run at this point
  meta: flush_handlers 

- name: Nsupdate A records
  when: inventory_hostname in groups['dns_master']
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ domain }}"
    type: "A"
    record: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ dns_a_records | dict2items }}"
  notify: restart bind9

- name: Nsupdate CNAME records
  when: inventory_hostname in groups['dns_master']
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ domain }}"
    type: "CNAME"
    record: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  notify: restart bind9

- name: Service bind
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: yes