# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: linux
    static_configs:
      - targets:
        {% for vm in groups['all'] %}
        - {{ vm }}:9100
        {% endfor %}

  - job_name: bind9
    static_configs:
      - targets:
        {% for vm in range(groups['dns_servers']|length) %}
        - ns{{ vm+1 }}:9119
        {% endfor %}

  - job_name: mysql
    static_configs:
      - targets:
        {% for vm in range(groups['db_servers']|length) %}
        - mysql{{ vm+1 }}:9104
        {% endfor %}

  - job_name: nginx
    static_configs:
      - targets:
        {% for vm in range(groups['web_servers']|length) %}
        - web{{ vm+1 }}:9113
        {% endfor %}

  - job_name: influx
    static_configs:
      - targets:
        {% for vm in groups['influxdb'] %}
        - {{ vm }}:9424
        {% endfor %}

  - job_name: haproxy
    static_configs:
      - targets:
        {% for vm in range(groups['haproxy']|length) %}
        - lb{{ vm+1 }}:9101
        {% endfor %}

  - job_name: keepalived
    static_configs:
      - targets:
        {% for vm in range(groups['haproxy']|length) %}
        - lb{{ vm+1 }}:9165
        {% endfor %}
